version: 2.1
jobs:
  init: # checkout and auto-lint
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive

      - run: npm i --production --ignore-scripts
      - run: cd library && npm i --production --ignore-scripts

      # save checkout & build
      - persist_to_workspace:
          root: '..'
          paths:
            - repo

  testContracts:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd contracts && npm i # --production causes issues with the gas reporter
      - run: cd contracts && npm run compile
      - run: cd contracts && npm run test

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/contracts/build
            - repo/contracts/node_modules

  buildWebsite:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd website && npm i # --production breaks the build
      - run: cd website && npm run build

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/website/dist
            - repo/website/node_modules

  buildDocs:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd docs && npm i --production
      - run: cd docs && npm run build

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/docs/docs/.vuepress/dist
            - repo/docs/node_modules

  lint:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      # lint and commit any changes, which may restart the build
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: npm run lint # includes --fix
      - run: bash .circleci/commit.sh

  push:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # Push website
      - run: bash .circleci/deploy-ghpages.sh
            
      # Deploy contracts
      - run: cd library && npm run deploy

      # Push artifact changes
      - run: bash .circleci/deploy-artifacts.sh

workflows:
  build:
    jobs:
      - init:
          filters:
            branches:
              ignore:
                - gh-pages
                - artifacts
      - testContracts:
          requires:
            - init
      - buildDocs:
          requires:
            - init
      - buildWebsite:
          requires:
            - init
      - lint:
          requires:
            - testContracts
            - buildWebsite
            - buildDocs
      - push:
          filters:
            branches:
              only:
                - master
          requires:
            - lint
