version: 2.1
jobs:
  checkoutAndNpm:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}-{{ checksum "library/package.json" }}-{{ checksum "contracts/package.json" }}-{{ checksum "website/package.json" }}

      - run: npm i
      - run: cd library && npm i && cd ..
      - run: cd contracts && npm i && cd ..
      - run: cd website && npm i && cd ..

      - save_cache:
          paths:
            - node_modules
            - package-lock.json
            - library/node_modules
            - library/package-lock.json
            - contracts/node_modules
            - contracts/package-lock.json
            - website/node_modules
            - website/package-lock.json
          key: npm-{{ checksum "package.json" }}-{{ checksum "library/package.json" }}-{{ checksum "contracts/package.json" }}-{{ checksum "website/package.json" }}

      - persist_to_workspace:
          root: '..'
          paths:
            - repo

  lintJs:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'
      - run: mkdir ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: npm run lint # includes --fix
      - run: bash .circleci/commit.sh

  lintSolidity:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      # run tests
      - run: cd contracts && npm run lint

  compileContracts:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd contracts && npm run compile

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/contracts/build

  testContracts:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd contracts && npm run test

  deployContracts:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              cd library && npm run deploy && cd ..
              bash .circleci/deploy-artifacts.sh
            fi

  buildWebsite:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd website && npm run build && cd ..

  deployWebsite:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              bash .circleci/deploy-ghpages.sh
            fi

  prLibraryChange:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      # todo open PR

workflows:
  build:
    jobs:
      - checkoutAndNpm:
          filters:
            branches:
              ignore:
                - gh-pages
                - artifacts
      - lintJs:
          requires:
            - checkoutAndNpm
      - lintSolidity:
          requires:
            - checkoutAndNpm
      - compileContracts:
          requires:
            - checkoutAndNpm
      - testContracts:
          requires:
            - compileContracts
      - deployContracts:
          requires:
            - compileContracts
      - buildWebsite:
          requires:
            - deployContracts
      - deployWebsite:
          requires:
            - buildWebsite
      #- prLibraryChange:
      #    requires:
      #      - deployContracts
