version: 2.1
jobs:
  init: # checkout and auto-lint
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      # save checkout
      - persist_to_workspace:
          root: '..'
          paths:
            - repo

      - restore_cache:
          keys:
            - v5-{{ checksum "package.json" }}

      - run: npm i --production --ignore-scripts

      # lint and commit any changes, which may restart the build
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: npm run lint # includes --fix
      - run: bash .circleci/commit.sh

      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: v5-{{ checksum "package.json" }}

  buildContracts:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - restore_cache:
          keys:
            - v5-{{ checksum "contracts/package.json" }}
      - run: cd contracts && npm i --production
      - save_cache:
          paths:
            - contracts/node_modules
            - contracts/package-lock.json
          key: v5-{{ checksum "contracts/package.json" }}

      - run: cd contracts && npm run compile

      # build library
      - restore_cache:
          keys:
            - v5-{{ checksum "library/package.json" }}
      - run: cd library && npm i --production
      - save_cache:
          paths:
            - library/node_modules
            - library/package-lock.json
          key: v5-{{ checksum "library/package.json" }}

      - run: cd library && npm run deploy

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/contracts/build
            - repo/library/artifacts

  testContracts:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - restore_cache:
          keys:
            - v5-{{ checksum "library/package.json" }}
      - restore_cache:
          keys:
            - v5-{{ checksum "contracts/package.json" }}

      - run: cd contracts && npm run test

  buildWebsite:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - restore_cache:
          keys:
            - v5-{{ checksum "library/package.json" }}
      - restore_cache:
          keys:
            - v5-{{ checksum "website/package.json" }}
      - run: cd website && npm i --production
      - save_cache:
          paths:
            - website/node_modules
            - website/package-lock.json
          key: v5-{{ checksum "website/package.json" }}

      - run: cd website && npm run build

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/website/dist

  buildDocs:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'


      - restore_cache:
          keys:
            - v5-{{ checksum "docs/package.json" }}
      - run: cd docs && npm i --production
      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: v5-{{ checksum "docs/package.json" }}

      - run: cd docs && npm run build

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/docs/docs/.vuepress/dist

  push:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: mkdir ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: bash .circleci/deploy-ghpages.sh
      - run: bash .circleci/deploy-artifacts.sh

workflows:
  build:
    jobs:
      - init:
          filters:
            branches:
              ignore:
                - gh-pages
                - artifacts
      - buildContracts:
          requires:
            - init
      - buildDocs:
          requires:
            - init
      - testContracts:
          requires:
            - init
            - buildContracts
      - buildWebsite:
          requires:
            - init
            - buildContracts
      - push:
          filters:
            branches:
              only:
                - master
          requires:
            - init
            - testContracts
            - buildWebsite
            - buildDocs
